(defproject ce2x "0.1.0-SNAPSHOT"
  :description "Clojure EDI to XML"
  :url "http://example.com/FIXME"
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [compojure "1.1.8"]
                 [org.milyn/milyn-smooks-edi "1.5"]
                 [org.milyn/milyn-edisax-parser "1.5"]
                 [org.milyn.edi.unedifact/d95a-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d95b-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d96a-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d96b-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d97a-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d97b-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d98a-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d98b-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d99a-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d99b-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d00a-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d00b-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d01a-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d01b-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d02a-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d02b-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d03a-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d03b-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d04a-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d04b-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d05a-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d05b-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d06a-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d06b-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d07a-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d07b-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d08a-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d08b-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d09a-mapping "1.5-SNAPSHOT"]
                 [org.milyn.edi.unedifact/d09b-mapping "1.5-SNAPSHOT"]
                 ; [org.milyn.edi.unedifact/d10a-mapping "1.5-SNAPSHOT"]
                 ; [org.milyn.edi.unedifact/d10b-mapping "1.5-SNAPSHOT"]
                 ; [org.milyn.edi.unedifact/d11a-mapping "1.5-SNAPSHOT"]
                 ; [org.milyn.edi.unedifact/d11b-mapping "1.5-SNAPSHOT"]
                 ; [org.milyn.edi.unedifact/d12a-mapping "1.5-SNAPSHOT"]
                 ; [org.milyn.edi.unedifact/d12b-mapping "1.5-SNAPSHOT"]
                 ; [org.milyn.edi.unedifact/d13a-mapping "1.5-SNAPSHOT"]
                 ; [org.milyn.edi.unedifact/d13b-mapping "1.5-SNAPSHOT"]
                 ; [org.milyn.edi.unedifact/d14a-mapping "1.5-SNAPSHOT"]
                 ]
  :java-source-paths ["src"]
  :plugins [[lein-ring "0.8.11"]]
  :ring {:handler ce2x.handler/app}
  :profiles
  {:dev {:dependencies [[javax.servlet/servlet-api "2.5"]
                        [ring-mock "0.1.5"]]}})
